### ISSUE TITLE
0.0.2 isn't available in Maven Central

### ISSUE THREAD

**Issue by bellemare** [grantwest/eventually-matchers#2]
Not sure where 0.0.2 artifact is available, but I can't find it. 0.0.1 is in maven central.
https://mvnrepository.com/artifact/com.github.grantwest.eventually/hamcrest-eventually-matchers

**Comment by grantwest** [comment]
Thanks for reporting this, I will get the 0.0.2 version published. For now 0.0.1 should work just fine. The only difference is this null pointer bug fix which you probably won't run into: https://github.com/grantwest/eventually-matchers/commit/e1b3ab74af2fb0808f34b38c85fde83bccc8ff76

**Comment by bellemare** [comment]
All good. I'm trying to get this working with JUnit5, which I don't think will be much difficulty actually. I'll let you know.

**Comment by grantwest** [comment]
I got a new release pushed to maven central. 0.0.3, there isn't anything new, 0.0.2 was half released and I just didn't want to deal with it. If you get it working for JUnit5, send me a pull request.
